// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// density_bounded.cpp
doubles mean_beta_densities_log(doubles log_xs, doubles log_one_minus_xs, doubles as, doubles bs, doubles log_beta_a_bs);
extern "C" SEXP _ggdist_mean_beta_densities_log(SEXP log_xs, SEXP log_one_minus_xs, SEXP as, SEXP bs, SEXP log_beta_a_bs) {
  BEGIN_CPP11
    return cpp11::as_sexp(mean_beta_densities_log(cpp11::as_cpp<cpp11::decay_t<doubles>>(log_xs), cpp11::as_cpp<cpp11::decay_t<doubles>>(log_one_minus_xs), cpp11::as_cpp<cpp11::decay_t<doubles>>(as), cpp11::as_cpp<cpp11::decay_t<doubles>>(bs), cpp11::as_cpp<cpp11::decay_t<doubles>>(log_beta_a_bs)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_ggdist_mean_beta_densities_log", (DL_FUNC) &_ggdist_mean_beta_densities_log, 5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ggdist(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
