// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wilkinson_bin_to_right_
Rcpp::IntegerVector wilkinson_bin_to_right_(const Rcpp::NumericVector& x, const double width);
RcppExport SEXP _ggdist_wilkinson_bin_to_right_(SEXP xSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(wilkinson_bin_to_right_(x, width));
    return rcpp_result_gen;
END_RCPP
}
// compact_swarm_naive_
SEXP compact_swarm_naive_(std::vector<Rcpp::NumericVector> xs, const double xsize, const double ysize, const int side);
RcppExport SEXP _ggdist_compact_swarm_naive_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<Rcpp::NumericVector> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_swarm_naive_(xs, xsize, ysize, side));
    return rcpp_result_gen;
END_RCPP
}
// compact_swarm_prog_
SEXP compact_swarm_prog_(std::vector<Rcpp::NumericVector> xs, const double xsize, const double ysize, const int side);
RcppExport SEXP _ggdist_compact_swarm_prog_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<Rcpp::NumericVector> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_swarm_prog_(xs, xsize, ysize, side));
    return rcpp_result_gen;
END_RCPP
}
// compact_swarm_prog_old_
SEXP compact_swarm_prog_old_(std::vector<Rcpp::NumericVector> xs, const double xsize, const double ysize, const int side);
RcppExport SEXP _ggdist_compact_swarm_prog_old_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<Rcpp::NumericVector> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_swarm_prog_old_(xs, xsize, ysize, side));
    return rcpp_result_gen;
END_RCPP
}
// compact_swarm_2_
SEXP compact_swarm_2_(std::vector<Rcpp::NumericVector> xs, const double xsize, const double ysize, const int side);
RcppExport SEXP _ggdist_compact_swarm_2_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<Rcpp::NumericVector> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_swarm_2_(xs, xsize, ysize, side));
    return rcpp_result_gen;
END_RCPP
}
// compact_swarm_grid_
SEXP compact_swarm_grid_(std::vector<Rcpp::NumericVector> xs, const double xsize, const double ysize, const int side);
RcppExport SEXP _ggdist_compact_swarm_grid_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<Rcpp::NumericVector> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_swarm_grid_(xs, xsize, ysize, side));
    return rcpp_result_gen;
END_RCPP
}
// grid_swarm_
SEXP grid_swarm_(std::vector<std::deque<double>> xs, const double xsize, const double ysize, const std::ptrdiff_t ygrid, const int side);
RcppExport SEXP _ggdist_grid_swarm_(SEXP xsSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP ygridSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::vector<std::deque<double>> >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const std::ptrdiff_t >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_swarm_(xs, xsize, ysize, ygrid, side));
    return rcpp_result_gen;
END_RCPP
}
// recenter_swarm_clusters_
SEXP recenter_swarm_clusters_(Rcpp::NumericVector& x_vec, Rcpp::NumericVector& y_vec, const double binwidth);
RcppExport SEXP _ggdist_recenter_swarm_clusters_(SEXP x_vecSEXP, SEXP y_vecSEXP, SEXP binwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type binwidth(binwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(recenter_swarm_clusters_(x_vec, y_vec, binwidth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggdist_wilkinson_bin_to_right_", (DL_FUNC) &_ggdist_wilkinson_bin_to_right_, 2},
    {"_ggdist_compact_swarm_naive_", (DL_FUNC) &_ggdist_compact_swarm_naive_, 4},
    {"_ggdist_compact_swarm_prog_", (DL_FUNC) &_ggdist_compact_swarm_prog_, 4},
    {"_ggdist_compact_swarm_prog_old_", (DL_FUNC) &_ggdist_compact_swarm_prog_old_, 4},
    {"_ggdist_compact_swarm_2_", (DL_FUNC) &_ggdist_compact_swarm_2_, 4},
    {"_ggdist_compact_swarm_grid_", (DL_FUNC) &_ggdist_compact_swarm_grid_, 4},
    {"_ggdist_grid_swarm_", (DL_FUNC) &_ggdist_grid_swarm_, 5},
    {"_ggdist_recenter_swarm_clusters_", (DL_FUNC) &_ggdist_recenter_swarm_clusters_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggdist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
