// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wilkinson_bin_to_right_
Rcpp::IntegerVector wilkinson_bin_to_right_(const Rcpp::NumericVector& x, const double width);
RcppExport SEXP _ggdist_wilkinson_bin_to_right_(SEXP xSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(wilkinson_bin_to_right_(x, width));
    return rcpp_result_gen;
END_RCPP
}
// grid_swarm_
SEXP grid_swarm_(std::deque<double> x, const double xsize, const double ysize, const std::size_t ygrid, const int side);
RcppExport SEXP _ggdist_grid_swarm_(SEXP xSEXP, SEXP xsizeSEXP, SEXP ysizeSEXP, SEXP ygridSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::deque<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type xsize(xsizeSEXP);
    Rcpp::traits::input_parameter< const double >::type ysize(ysizeSEXP);
    Rcpp::traits::input_parameter< const std::size_t >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_swarm_(x, xsize, ysize, ygrid, side));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggdist_wilkinson_bin_to_right_", (DL_FUNC) &_ggdist_wilkinson_bin_to_right_, 2},
    {"_ggdist_grid_swarm_", (DL_FUNC) &_ggdist_grid_swarm_, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggdist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
