# Generated by cpp11: do not edit by hand

mean_beta_densities_log <- function(log_xs, log_one_minus_xs, as, bs, log_beta_a_bs) {
  .Call(`_ggdist_mean_beta_densities_log`, log_xs, log_one_minus_xs, as, bs, log_beta_a_bs)
}
