# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wilkinson_bin_to_right_ <- function(x, width) {
    .Call(`_ggdist_wilkinson_bin_to_right_`, x, width)
}

unwrap_promise_ <- function(x) {
    .Call(`_ggdist_unwrap_promise_`, x)
}

find_promise_ <- function(name, env) {
    .Call(`_ggdist_find_promise_`, name, env)
}

promise_expr_ <- function(promise) {
    .Call(`_ggdist_promise_expr_`, promise)
}

promise_env_ <- function(promise) {
    .Call(`_ggdist_promise_env_`, promise)
}

is_waived_ <- function(x) {
    .Call(`_ggdist_is_waived_`, x)
}

dots_to_list_ <- function(dots) {
    .Call(`_ggdist_dots_to_list_`, dots)
}

